In [1]:
! pip install numpy

## numpy --> numpy is a open source library that is used for scientific computation

## why we use numpy whenever we have list ?
    1.homogeneous data type
    2.memory less consume
    3.less time consume

In [4]:
import numpy as np

In [5]:
a=[12,3,4,2,43]
type(a)

list

In [6]:
a=np.array(a)
type(a)

numpy.ndarray

In [7]:
b=np.array(a)
b

array([12,  3,  4,  2, 43])

In [8]:
type(b)

numpy.ndarray

 ## dimension ==>
    1-D element exist in x direction
    2-D element exist in x and y direction
    3-D element exist in x,y,z direction

In [9]:
print("total shape",b.shape)
print("total number of element",b.size)
print("total dimension :",b.ndim)

total shape (5,)
total number of element 5
total dimension : 1


# 2D array

In [17]:
a=[[1,234,4],[32,44,3],[323,43,4]]
a

[[1, 234, 4], [32, 44, 3], [323, 43, 4]]

In [18]:
b=np.array(a)
b

array([[  1, 234,   4],
       [ 32,  44,   3],
       [323,  43,   4]])

In [19]:
type(b)

numpy.ndarray

In [20]:
print("total shape",b.shape)
print("total number of element",b.size)
print("total dimension :",b.ndim)

total shape (3, 3)
total number of element 9
total dimension : 2


## how can we create user defined array?

In [22]:
a=[]
size=int(input("Enter size:"))
for i in range(size):
    val=int(input("Enter the numer:"))
    a.append(val)
b=np.array(a)
b

Enter size:1
Enter the numer:2


array([2])

# Numpy Function
 images--> are store inn pixels(0-255)==> 0px- black 255px- white ==>normalize - (0,1)px
 
 a. black and white image--> height and width
 
 b. colorful image--> height,width and colour channel(RGB)
 
 matrix==> rows=columns(symmetric matrix) and rows!=columns(asymmetric matrix)

 random number generator==> random module


# 1. Zeros() ==> it will create an array in which all the values are 0.


In [24]:
a=np.zeros(3)

In [25]:
a

array([0., 0., 0.])

In [26]:
a=np.zeros((3,4))

In [27]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 2. Ones() ==> it will create an array in which all the values are 1.

In [28]:
a=np.ones(3)

In [29]:
a

array([1., 1., 1.])

In [30]:
a=np.ones((3,4))

In [31]:
a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
a.shape

(3, 4)

In [34]:
# 3. eye() ==> It will craete an array in which diagonal poistion element are 1 and rest are 0.

In [36]:
a=np.eye(3) #symetric matrix
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
a=np.eye(3,4) #asymetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
# 4. diag() ==> It will create an array in which we cam customize our diagonal poistion element 

In [41]:
a=np.diag([1,2,4,5,6])
a

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 4, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 6]])

# 5. RANDOM MODULE
- uses
    # a.Otp generation
    # b. dataset--> dummy colun add
    # c. randomly weight initialise

In [43]:
# a. randint(min,max,total_number)

In [45]:
a=np.random.randint(1,10,3)
a

array([9, 7, 7])

In [46]:
# b. rand(total_number)--> it will return number from 0 to 1
a=np.random.rand(5)
a

array([0.37594003, 0.43041852, 0.94386185, 0.83885555, 0.12202713])

In [47]:
# c. randn() ==> standard normal distribtion

In [49]:
a=np.random.randn(5)
a

array([-1.37640104, -0.50414555, -1.08680261,  0.91713124,  0.34200078])

In [50]:
# d. seed() ==> it will fix our data once the data has ben generated

In [51]:
np.random.seed(3)
a=np.random.randint(1,10,3)
a

array([9, 4, 9])

# View v/s Copy

In [52]:
# view is modification in original data
a=np.array([10,20,30,40,50,60,70])
b=a[2:5]
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70])

In [53]:
# copy not modifiy in original data
a=np.array([10,20,30,40,50,60,70])
b=a[2:5].copy()
b[:]=0
a

array([10, 20, 30, 40, 50, 60, 70])

# reshaping the data

   #rows*column=total element
   
   eg.
   
   if we have total element =12
   then ->
   
       1*12,12*1
       2*6,6*2
       3*4,4*3

In [54]:
a=np.random.randint(1,50,12)
a

array([ 9,  1, 22, 20, 11, 44, 42, 11, 22, 39, 33, 21])

In [56]:
a.shape

(12,)

In [57]:
a.reshape(2,6)

array([[ 9,  1, 22, 20, 11, 44],
       [42, 11, 22, 39, 33, 21]])

In [58]:
a.reshape(6,2)

array([[ 9,  1],
       [22, 20],
       [11, 44],
       [42, 11],
       [22, 39],
       [33, 21]])

In [59]:
a=np.random.randint(1,100,72)
a

array([45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61,  2, 52, 91, 70, 98,
       30, 25, 63,  8, 44, 34, 80, 49, 38, 21, 95, 50, 22, 79, 29, 55,  1,
       65, 19, 64, 38, 57, 57, 72, 38, 47, 34,  2, 86, 75, 92, 17, 81, 33,
       17, 19, 76, 56, 97, 96, 14, 38, 31, 49, 62, 34, 53,  3, 29, 37, 91,
       45, 49, 60, 75])

In [61]:
a.reshape(1,72)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61,  2, 52, 91, 70,
        98, 30, 25, 63,  8, 44, 34, 80, 49, 38, 21, 95, 50, 22, 79, 29,
        55,  1, 65, 19, 64, 38, 57, 57, 72, 38, 47, 34,  2, 86, 75, 92,
        17, 81, 33, 17, 19, 76, 56, 97, 96, 14, 38, 31, 49, 62, 34, 53,
         3, 29, 37, 91, 45, 49, 60, 75]])

In [62]:
a.reshape(2,36)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61,  2, 52, 91, 70,
        98, 30, 25, 63,  8, 44, 34, 80, 49, 38, 21, 95, 50, 22, 79, 29,
        55,  1, 65, 19],
       [64, 38, 57, 57, 72, 38, 47, 34,  2, 86, 75, 92, 17, 81, 33, 17,
        19, 76, 56, 97, 96, 14, 38, 31, 49, 62, 34, 53,  3, 29, 37, 91,
        45, 49, 60, 75]])

In [63]:
a.reshape(3,24)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61,  2, 52, 91, 70,
        98, 30, 25, 63,  8, 44, 34, 80],
       [49, 38, 21, 95, 50, 22, 79, 29, 55,  1, 65, 19, 64, 38, 57, 57,
        72, 38, 47, 34,  2, 86, 75, 92],
       [17, 81, 33, 17, 19, 76, 56, 97, 96, 14, 38, 31, 49, 62, 34, 53,
         3, 29, 37, 91, 45, 49, 60, 75]])

In [64]:
a.reshape(4,18)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61,  2, 52, 91, 70,
        98, 30],
       [25, 63,  8, 44, 34, 80, 49, 38, 21, 95, 50, 22, 79, 29, 55,  1,
        65, 19],
       [64, 38, 57, 57, 72, 38, 47, 34,  2, 86, 75, 92, 17, 81, 33, 17,
        19, 76],
       [56, 97, 96, 14, 38, 31, 49, 62, 34, 53,  3, 29, 37, 91, 45, 49,
        60, 75]])

In [65]:
a.reshape(6,12)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67,  3, 64, 61],
       [ 2, 52, 91, 70, 98, 30, 25, 63,  8, 44, 34, 80],
       [49, 38, 21, 95, 50, 22, 79, 29, 55,  1, 65, 19],
       [64, 38, 57, 57, 72, 38, 47, 34,  2, 86, 75, 92],
       [17, 81, 33, 17, 19, 76, 56, 97, 96, 14, 38, 31],
       [49, 62, 34, 53,  3, 29, 37, 91, 45, 49, 60, 75]])

In [67]:
a.reshape(8,9)

array([[45, 94, 40, 15, 27, 82, 91, 23, 67],
       [ 3, 64, 61,  2, 52, 91, 70, 98, 30],
       [25, 63,  8, 44, 34, 80, 49, 38, 21],
       [95, 50, 22, 79, 29, 55,  1, 65, 19],
       [64, 38, 57, 57, 72, 38, 47, 34,  2],
       [86, 75, 92, 17, 81, 33, 17, 19, 76],
       [56, 97, 96, 14, 38, 31, 49, 62, 34],
       [53,  3, 29, 37, 91, 45, 49, 60, 75]])

In [68]:
a.reshape(9,8)

array([[45, 94, 40, 15, 27, 82, 91, 23],
       [67,  3, 64, 61,  2, 52, 91, 70],
       [98, 30, 25, 63,  8, 44, 34, 80],
       [49, 38, 21, 95, 50, 22, 79, 29],
       [55,  1, 65, 19, 64, 38, 57, 57],
       [72, 38, 47, 34,  2, 86, 75, 92],
       [17, 81, 33, 17, 19, 76, 56, 97],
       [96, 14, 38, 31, 49, 62, 34, 53],
       [ 3, 29, 37, 91, 45, 49, 60, 75]])

# Conditional selection inn numpy

In [70]:
a=np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [72]:
a<10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False])

In [75]:
b=a>10
a[b]

array([11, 12, 13, 14, 15])

In [76]:
c=a<10
a[c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

In [79]:
a[a%2!=0]

array([ 1,  3,  5,  7,  9, 11, 13, 15])

In [80]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [81]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [82]:
a+b

array([[ 6,  8],
       [10, 12]])

In [83]:
a-b

array([[-4, -4],
       [-4, -4]])

In [84]:
a*b  ## yeh wrong hai ,matrix multiplication

array([[ 5, 12],
       [21, 32]])

In [86]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [88]:
a=np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [90]:
np.sum(a)

45

In [92]:
np.sum(a,axis=1) ## row wise total

array([ 6, 15, 24])

In [93]:
np.sum(a,axis=0) ## column wise total

array([12, 15, 18])

# Unique()
    - it will return unique values or eliminate duplicates values
    - it will return 3 array
        1.unique values of array
        2.indexing of original value
        3.return frequency of each unique value

In [94]:
a=np.array([1,2,2,2,2,4,5,2,3,4,4,6,3])
a

array([1, 2, 2, 2, 2, 4, 5, 2, 3, 4, 4, 6, 3])

In [95]:
np.unique(a,return_index=True,return_counts=True)

(array([1, 2, 3, 4, 5, 6]),
 array([ 0,  1,  8,  5,  6, 11]),
 array([1, 5, 2, 3, 1, 1]))

# linspace() 
    - It will combined in which difference of each value will be equal

In [97]:
a=np.linspace(1,2,5)
a

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

# stacking in numpy
    1. hstack() --> It will combined multiple array into horizonatlly
    2. vstack() --> It will combined multiple array into vertically

In [98]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)

In [99]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [100]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])