In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
a=[1,2,4]
np.array(a)

array([1, 2, 4])

In [3]:
np.array([1,2,4,5])

array([1, 2, 4, 5])

In [8]:
np.array((1,2,4,5))

array([1, 2, 4, 5])

In [9]:
type(np.array([1,2,4,5]))

numpy.ndarray

In [10]:
type(np.array((1,2,4,5)))

numpy.ndarray

In [ ]:
ls=[[1,2,3],[3,4,5],[6,7,8]]

In [12]:
np.array(ls)

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
type(np.array(ls))

numpy.ndarray

In [14]:
ls=[]
size=int(input("Enter the number of element in array:"))
for i in range(size):
    val=int(input("Enter the numer:"))
    ls.append(val)
np.array(ls)

Enter the number of element in array:1
Enter the numer:2


array([2])

In [15]:
#numpy function
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.ones((3,3)).shape

(3, 3)

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [23]:
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [24]:
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [34]:
np.random.rand(5)

array([7.20324493e-01, 1.14374817e-04, 3.02332573e-01, 1.46755891e-01,
       9.23385948e-02])

In [28]:
np.random.randint(1,10,5)

array([9, 4, 1, 5, 9])

In [29]:
np.random.randn(5)

array([-1.07823853, -0.42520218,  0.26709542,  1.3168977 ,  0.76585207])

In [39]:
np.random.random()

0.7203244934421581

In [40]:
np.random.seed(1)
np.random.random()

0.417022004702574

In [42]:
a=np.array([1,2,3,4,56,])
b=a[2:5]
b

array([ 3,  4, 56])

In [44]:
b[:]=0
b

array([0, 0, 0])

In [45]:
a

array([1, 2, 0, 0, 0])

In [46]:
a=np.array([1,2,3,4,56,])
b=a[2:5].copy()
b

array([ 3,  4, 56])

In [47]:
b[:]=0
b

array([0, 0, 0])

In [48]:
a

array([ 1,  2,  3,  4, 56])

In [52]:
a=np.random.randint(1,16,16)
a.reshape(4,4)

array([[ 3,  5, 12, 13],
       [11, 13, 14, 15],
       [ 3,  5,  8,  8],
       [10,  2,  8, 15]])

In [55]:
a=np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
a>5

array([False, False, False, False, False,  True,  True,  True,  True])

In [57]:
a<5

array([ True,  True,  True,  True, False, False, False, False, False])

In [59]:
b=a<5
b

array([ True,  True,  True,  True, False, False, False, False, False])

In [60]:
a[b]

array([1, 2, 3, 4])

In [61]:
b=a>5
b

array([False, False, False, False, False,  True,  True,  True,  True])

In [62]:
a[b]

array([6, 7, 8, 9])

In [63]:
a[a%2==0]

array([2, 4, 6, 8])

In [64]:
a[a%2!=0]

array([1, 3, 5, 7, 9])

In [65]:
a=np.arange(1,5).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [67]:
b=np.arange(5,9).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [68]:
a+b

array([[10, 12],
       [14, 16]])

In [69]:
a-b

array([[0, 0],
       [0, 0]])

In [70]:
a*b

array([[25, 36],
       [49, 64]])

In [71]:
a.dot(b)

array([[ 67,  78],
       [ 91, 106]])

In [72]:
a=np.arange(1,17).reshape(4,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [73]:
np.sum(a,axis=0)

array([28, 32, 36, 40])

In [74]:
np.sum(a,axis=1)

array([10, 26, 42, 58])

In [76]:
a=np.random.randint(1,5,16)
a

array([4, 3, 2, 1, 3, 2, 4, 4, 3, 4, 2, 1, 4, 2, 2, 4])

In [78]:
np.unique(a)

array([1, 2, 3, 4])

In [79]:
np.unique(a,return_counts=True,return_index=True)

(array([1, 2, 3, 4]), array([3, 2, 1, 0]), array([2, 5, 3, 6]))

In [80]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [81]:
a=np.arange(1,5)
b=np.arange(5,9)
c=np.arange(9,13)